### ISSUE TITLE
Clear deleted files

### ISSUE THREAD

**Issue by CastixGitHub** [nicotine-plus/nicotine-plus#2084]
### Describe the solution you'd like
I'd like to clear the files I deleted from the file system

### Additional context
I downloaded some tracks, I listened to them, I decided to delete them, they are still listed in the downloads list.

Thanks

**Comment by mathiascode** [comment]
There are buttons/menu items to clear completed downloads from the list.

I don't think some kind of file system monitoring to keep lists in sync is something we want to implement, in terms of complexity and performance.

**Comment by slook** [comment]
> some kind of file system monitoring to keep lists in sync

Agreed this would be very expensive on system resources, and does not need to be implemented.

When clicking on an item for opening, it is unhelpful that there isn't any sort of UI feedback for files which have gone missing. It would be expected that something happens such as the Status be changed to "Local file error", but instead nothing occurs atall, indicating that some required functionality is indeed lacking.

**Comment by mathiascode** [comment]
I thought we had a log message. Maybe it only prints in the terminal?

**Comment by slook** [comment]
No, on default action/Send to Player there is nothing in any log category nor any output in the terminal.

**Comment by mathiascode** [comment]
> No, on default action/Send to Player there is nothing in any log category nor any output in the terminal.

Fixed in 61d21cd60a1cda8ac13c3bb24a16a967989339ea

**Comment by CastixGitHub** [comment]
Hi again, I wan't asking for full fs monitoring, just another option within clear menus, that checks the transfers and verify if they still exists, clearing the non-existing ones. on-demand.
I didn't get if that would be a welcomed PR due to the increase of maintenance needed

**Comment by slook** [comment]
In my use case also it is annoying that the Downloads list does become full of missing files, since they are usually moved elsewhere, so a 'Clear All > 'Deleted' function would infact be useful.

My only concern is that the other Clear All functions work on the Status of the items, whereas the proposed new function would have to have it's own logic to identify items for removal, resulting in the effect being a mystery until it is invoked.
