### ISSUE TITLE
last frame.py update fails, Nicotine 1.4.3

### ISSUE THREAD

**Issue by zebulon-1st** [Nicotine-Plus/nicotine-plus#246]
After updated with a `git pull`, frame.py was the only file updated.
And now, I can't run without this error message:

```
$ ./nicotine 
Traceback (most recent call last):
  File "./nicotine", line 255, in <module>
    run()
  File "./nicotine", line 231, in run
    app = frame.MainApp(data_dir, config, plugins, trayicon, hidden, bindip, port)
  File "/media/joe/Helium1/Sources/nicotine-plus/pynicotine/gtkgui/frame.py", line 3628, in __init__
    self.frame = NicotineFrame(data_dir, config, plugins, trayicon, start_hidden, bindip, port)
  File "/media/joe/Helium1/Sources/nicotine-plus/pynicotine/gtkgui/frame.py", line 543, in __init__
    self.userlist = UserList(self)
  File "/media/joe/Helium1/Sources/nicotine-plus/pynicotine/gtkgui/userlist.py", line 163, in __init__
    time_from_epoch = time.mktime(time.strptime(last_seen, "%m/%d/%Y %H:%M:%S"))
  File "/usr/lib/python3.5/_strptime.py", line 504, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data 'Jamais vu' does not match format '%m/%d/%Y %H:%M:%S'
```
So, Nicotine fails

---
Note : 'Jamais vu' [fr] == 'never seen' [en]

**Comment by mathiascode** [comment]
Could you check if the following branch fixes the issue?
`git clone -b buddylist https://github.com/mathiascode/nicotine-plus`

**Comment by zebulon-1st** [comment]
Well, it seems better. No fail, as before, on date formatting.

Here are stderr output :
```

(nicotine:26643): Gtk-WARNING **: Allocating size to GtkWindow 0x563b98050500 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nicotine:26643): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(nicotine:26643): Gtk-WARNING **: Allocating size to GtkWindow 0x563b98050500 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(nicotine:26643): Gtk-WARNING **: Allocating size to GtkWindow 0x563b98050500 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```
plus, these lines repeating many many :
```
Traceback (most recent call last):
  File "nicotine-plus/pynicotine/gtkgui/frame.py", line 1426, in OnNetworkEvent
    self.np.events[i.__class__](i)
  File "nicotine-plus/pynicotine/pynicotine.py", line 1466, in FileSearchResult
    self.search.ShowResult(msg, i.username, country)
  File "nicotine-plus/pynicotine/gtkgui/search.py", line 453, in ShowResult
    counter = len(search[2].all_data) + 1
AttributeError: 'NoneType' object has no attribute 'all_data'
```

**Comment by mathiascode** [comment]
The AttributeError issue should now be fixed in the same branch. Can you confirm?

Did you do anything specific to trigger the Gdk/Gtk warnings?

**Comment by zebulon-1st** [comment]
I still have the issue (v1.4.3 branch master), the same error :
```
$ ./nicotine 
Traceback (most recent call last):
  File "./nicotine", line 255, in <module>
    run()
  File "./nicotine", line 231, in run
    app = frame.MainApp(data_dir, config, plugins, trayicon, hidden, bindip, port)
  File "nicotine-plus/pynicotine/gtkgui/frame.py", line 3627, in __init__
    self.frame = NicotineFrame(data_dir, config, plugins, trayicon, start_hidden, bindip, port)
  File "nicotine-plus/pynicotine/gtkgui/frame.py", line 543, in __init__
    self.userlist = UserList(self)
  File "nicotine-plus/pynicotine/gtkgui/userlist.py", line 163, in __init__
    time_from_epoch = time.mktime(time.strptime(last_seen, "%m/%d/%Y %H:%M:%S"))
  File "/usr/lib/python3.5/_strptime.py", line 504, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data 'Jamais vu' does not match format '%m/%d/%Y %H:%M:%S'
```

For the GTK warnings, I do nothing special.
I just call nicotine, in a shell, without any option or argument, as written above.

I use Debian 9 (always updated), with MATE (1.16.2) desktop.
libgtk2.0-0 / 2.24.31-2
libgtk-3-0 / 3.22.11-1
libwxgtk3.0-0v5 / 3.0.2+dfsg-4
python-gtk2 / 2.24.0-5.1
python-wxgtk3.0 / 3.0.2.0+dfsg-4

**Comment by zebulon-1st** [comment]
Oops, sorry.

As you asked, in the same branch, the Attribute issue is now fixed. It does not appear any more.

**Comment by zebulon-1st** [comment]
The initial ValueError seems to have been fixed, too, on branch master ?

**Comment by mathiascode** [comment]
Yup, only the Gtk/Gdk warnings aren't fixed.

**Comment by zebulon-1st** [comment]
Ok. So, Do I have to close this issue, now ?

**Comment by mathiascode** [comment]
We can keep it open until the warnings are fixed.

**Comment by zebulon-1st** [comment]
Ok.
